namespace MASA.PasswordGenerator.Core.Constants;

public static class CharacterSets
{
    public const string Uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public const string Lowercase = "abcdefghijklmnopqrstuvwxyz";
    public const string Digits = "0123456789";
    public const string StandardSymbols = "!@#$%^&*()_+-=[]{}|;:,.<>?";
    public const string AllSymbols = "!@#$%^&*()_+-=[]{}|;:,.<>?/~`'\"\\";

    // Similar characters that can cause visual confusion
    public const string SimilarCharacters = "il1Lo0O";

    // Ambiguous symbols that might break scripts/parsers or be easily misread
    public const string AmbiguousSymbols = "{}[]()/\\'\"`~,;:.<>";

    // Pre-curated default wordlist for Diceware Passphrase generation
    public static readonly string[] DefaultWordList =
    [
        "ability", "able", "about", "above", "accept", "account", "across", "action", "activity", "actor",
        "actress", "actual", "address", "admit", "adopt", "advance", "advice", "affect", "afford", "afraid",
        "after", "again", "against", "agency", "agent", "agree", "ahead", "airline", "airport", "alarm",
        "album", "alcohol", "alive", "allow", "almost", "alone", "along", "already", "also", "always",
        "amazing", "among", "amount", "ancient", "animal", "annual", "another", "answer", "antenna", "anxious",
        "anybody", "anyone", "anyway", "apart", "apology", "appear", "apple", "apply", "approve", "archer",
        "area", "argue", "armor", "around", "arrange", "arrest", "arrive", "arrow", "article", "artist",
        "asleep", "aspect", "assault", "asset", "assist", "assume", "athlete", "atlas", "atom", "attack",
        "attempt", "attend", "attitude", "attract", "auction", "audit", "august", "author", "auto", "autumn",
        "avenue", "average", "avoid", "awake", "aware", "awesome", "awful", "baboon", "baby", "bacon",
        "badge", "bagel", "baker", "balance", "balcony", "ball", "bamboo", "banana", "banner", "barber",
        "bargain", "barrel", "barrier", "base", "basic", "basket", "battle", "beach", "beacon", "bean",
        "beauty", "because", "become", "before", "begin", "behave", "behind", "believe", "belong", "below",
        "bench", "benefit", "berry", "beside", "better", "between", "beyond", "bicycle", "biology", "bird",
        "birth", "bitter", "black", "blade", "blame", "blanket", "blast", "blaze", "blend", "bless",
        "blind", "block", "blossom", "blue", "board", "boat", "body", "boiler", "bomb", "bonus",
        "boost", "border", "boring", "borrow", "boss", "bottle", "bottom", "bounce", "boundary", "brave",
        "bread", "breeze", "brick", "bridge", "brief", "bright", "bring", "brisk", "bronze", "brother",
        "brush", "bubble", "budget", "buffalo", "build", "bullet", "bundle", "bunker", "burden", "burger",
        "butter", "button", "cabin", "cable", "cactus", "cage", "camera", "camp", "canary", "cancel",
        "candle", "canvas", "canyon", "capable", "capital", "captain", "carbon", "card", "cargo", "carpet",
        "carrot", "carry", "cart", "cascade", "castle", "casual", "catalog", "catch", "category", "cattle",
        "cause", "caution", "cave", "ceiling", "celery", "cement", "census", "century", "cereal", "chain",
        "chair", "chalk", "champion", "change", "channel", "chapter", "charge", "charity", "charm", "chart",
        "chase", "cheap", "check", "cheese", "cherry", "chest", "chicken", "chief", "child", "chimney",
        "choice", "chronic", "chuckle", "church", "cinema", "circle", "citizen", "city", "civil", "claim",
        "clamp", "clarity", "clash", "classic", "clean", "clerk", "clever", "click", "client", "cliff",
        "climate", "climb", "clinic", "clock", "clone", "close", "cloth", "cloud", "clover", "cluster",
        "coach", "coast", "coconut", "coffee", "coin", "collect", "colony", "color", "column", "combine",
        "comfort", "comic", "common", "company", "compass", "compose", "concert", "conduct", "confirm", "connect",
        "control", "cookie", "copper", "coral", "corner", "correct", "cotton", "couch", "country", "courage",
        "cousin", "cover", "cradle", "craft", "crane", "crater", "crawl", "crazy", "cream", "credit",
        "creek", "crew", "cricket", "crime", "crisp", "critic", "cross", "crouch", "crowd", "crucial",
        "cruise", "crumble", "crystal", "cube", "culture", "cupboard", "curious", "current", "curtain", "curve",
        "cushion", "custom", "cycle", "cylinder", "damage", "dance", "danger", "daring", "dark", "darling",
        "dash", "data", "date", "dawn", "daylight", "debate", "debris", "decade", "december", "decide",
        "declare", "decor", "decrease", "deep", "defeat", "defender", "define", "defy", "degree", "delay",
        "deliver", "demand", "demise", "denial", "dense", "deposit", "depth", "deputy", "derive", "describe",
        "desert", "design", "desk", "despair", "destroy", "detail", "detect", "develop", "device", "devote",
        "diagram", "diamond", "diary", "diesel", "differ", "digital", "dignity", "dilemma", "dinner", "dinosaur",
        "direct", "dirt", "disable", "disaster", "disc", "discover", "disease", "dish", "dismiss", "display",
        "distance", "divert", "divide", "divorce", "dizzy", "doctor", "document", "dolphin", "domain", "donate",
        "donkey", "donor", "door", "dose", "double", "dove", "draft", "dragon", "drama", "drastic",
        "draw", "dream", "dress", "drift", "drill", "drink", "drip", "drive", "drop", "drum",
        "dryer", "duck", "duct", "dumb", "dune", "during", "dust", "dwarf", "dynamic", "eager",
        "eagle", "early", "earn", "earth", "easily", "east", "echo", "ecology", "economy", "edge",
        "edit", "educate", "effort", "eight", "either", "elbow", "elder", "electric", "elegant", "element",
        "elephant", "elevator", "elite", "embark", "embody", "embrace", "emerge", "emotion", "employ", "empower",
        "empty", "enable", "enact", "endless", "endorse", "enemy", "energy", "enforce", "engage", "engine",
        "enhance", "enjoy", "enlist", "enough", "enrich", "enroll", "ensure", "enter", "entire", "entry",
        "envelope", "episode", "equal", "equip", "era", "erase", "erosion", "error", "erupt", "escape",
        "essay", "essence", "estate", "eternal", "ethics", "evidence", "evil", "evoke", "evolve", "exact",
        "example", "excess", "exchange", "excite", "exclude", "excuse", "execute", "exercise", "exhaust", "exhibit",
        "exile", "exist", "exit", "exotic", "expand", "expect", "expire", "explain", "expose", "express",
        "extend", "extra", "fabric", "face", "faculty", "fade", "faint", "faith", "fall", "false",
        "fame", "family", "famous", "fancy", "fantasy", "farmer", "fashion", "fast", "fatal", "father",
        "fatigue", "fault", "favorite", "feature", "february", "federal", "feedback", "fellow", "female", "fence",
        "festival", "fetch", "fever", "fiber", "fiction", "field", "figure", "filter", "final", "finance",
        "finder", "finger", "finish", "fire", "firm", "first", "fiscal", "fish", "fitness", "flame",
        "flash", "flavor", "flee", "flight", "flip", "float", "flock", "floor", "flower", "fluid",
        "flush", "flyer", "focus", "foggy", "foil", "fold", "follow", "food", "foot", "force",
        "forest", "forget", "fork", "fortune", "forum", "forward", "fossil", "foster", "found", "fox",
        "fragile", "frame", "freedom", "freeze", "fresh", "friend", "frog", "front", "frost", "frozen",
        "fruit", "fuel", "full", "fumble", "function", "fungus", "furnace", "future", "gadget", "gain",
        "galaxy", "gallery", "game", "gap", "garage", "garbage", "garden", "garlic", "garment", "gasoline",
        "gateway", "gather", "gauge", "gaze", "general", "genius", "genre", "gentle", "genuine", "gesture",
        "ghost", "giant", "gift", "giggle", "ginger", "giraffe", "girl", "glance", "glare", "glass",
        "glide", "glimpse", "globe", "gloom", "glory", "glove", "glow", "glue", "goat", "goddess",
        "gold", "golden", "golf", "goose", "gospel", "gossip", "govern", "gown", "grab", "grace",
        "grain", "grand", "grant", "grape", "grass", "gravity", "great", "green", "grid", "grief",
        "grit", "grocery", "group", "grow", "grunt", "guard", "guess", "guide", "guilt", "guitar",
        "gun", "gym", "habit", "habitat", "hair", "half", "hammer", "hamster", "hand", "handle",
        "harbor", "hard", "harsh", "harvest", "hat", "have", "hawk", "hazard", "head", "health",
        "heart", "heavy", "hedgehog", "height", "hello", "helmet", "help", "hen", "hero", "hidden",
        "high", "hill", "hint", "hip", "hire", "history", "hobby", "hockey", "hold", "hole",
        "holiday", "hollow", "home", "honey", "hood", "hope", "horizon", "horn", "horror", "horse",
        "hospital", "host", "hotel", "hour", "hover", "hub", "huge", "human", "humble", "humor",
        "hundred", "hungry", "hunt", "hurdle", "hurry", "hurt", "husband", "hybrid", "ice", "icon",
        "idea", "identify", "idle", "ignore", "illness", "image", "imitate", "immense", "immune", "impact",
        "impose", "improve", "impulse", "inch", "include", "income", "increase", "index", "indicate", "indoor",
        "industry", "infant", "inflict", "inform", "inhale", "inherit", "initial", "inject", "injury", "inmate",
        "inner", "innocent", "input", "inquiry", "insane", "insect", "inside", "inspire", "install", "intact",
        "interest", "into", "invest", "invite", "involve", "iron", "island", "isolate", "issue", "item",
        "ivory", "jacket", "jaguar", "jar", "jazz", "jealous", "jeans", "jelly", "jewel", "job",
        "join", "joke", "journey", "joy", "judge", "juice", "jump", "jungle", "junior", "junk",
        "jury", "just", "kangaroo", "keen", "keep", "ketchup", "key", "kick", "kid", "kidney",
        "kind", "kingdom", "kiss", "kit", "kitchen", "kite", "kitten", "kiwi", "knee", "knife",
        "knock", "know", "lab", "label", "labor", "ladder", "lady", "lake", "lamp", "language",
        "laptop", "large", "later", "latin", "laugh", "laundry", "lava", "law", "lawn", "lawsuit",
        "layer", "lazy", "leader", "leaf", "learn", "leave", "lecture", "left", "leg", "legal",
        "legend", "leisure", "lemon", "lend", "length", "lens", "leopard", "lesson", "letter", "level",
        "liberty", "library", "license", "life", "lift", "light", "like", "limb", "limit", "link",
        "lion", "liquid", "list", "little", "live", "lizard", "load", "loan", "lobster", "local",
        "lock", "logic", "lonely", "long", "loop", "lottery", "loud", "lounge", "love", "loyal",
        "lucky", "luggage", "lumber", "lunar", "lunch", "luxury", "lyrics", "machine", "mad", "magic",
        "magnet", "maid", "mail", "main", "major", "make", "mammal", "man", "manage", "mandate",
        "mango", "mansion", "manual", "maple", "marble", "march", "margin", "marine", "market", "marriage",
        "mask", "mass", "master", "match", "material", "matrix", "matter", "maximum", "maze", "meadow",
        "mean", "measure", "meat", "mechanic", "medal", "media", "melody", "melt", "member", "memory",
        "mention", "menu", "mercy", "merge", "merit", "merry", "mesh", "message", "metal", "method",
        "middle", "midnight", "military", "milk", "million", "mimic", "mind", "minimum", "minor", "minute",
        "miracle", "mirror", "misery", "miss", "mistake", "mix", "mixed", "mixture", "mobile", "model",
        "modify", "mom", "moment", "monitor", "monkey", "monster", "month", "moon", "moral", "more",
        "morning", "mosquito", "mother", "motion", "motor", "mountain", "mouse", "move", "movie", "much",
        "muffin", "mule", "multiply", "muscle", "museum", "mushroom", "music", "must", "mutual", "myself",
        "mystery", "myth", "naive", "name", "napkin", "narrow", "nasty", "nation", "nature", "near",
        "neck", "need", "negative", "neglect", "neither", "nephew", "nerve", "nest", "net", "network",
        "neutral", "never", "news", "next", "nice", "night", "noble", "noise", "nominee", "noodle",
        "normal", "north", "nose", "notable", "note", "nothing", "notice", "novel", "now", "nuclear",
        "number", "nurse", "nut", "oak", "obey", "object", "oblige", "obscure", "observe", "obtain",
        "obvious", "ocean", "october", "odor", "off", "offer", "office", "often", "oil", "okay",
        "old", "olive", "olympic", "omit", "once", "one", "onion", "online", "only", "open",
        "opera", "opinion", "oppose", "option", "orange", "orbit", "orchard", "order", "ordinary", "organ",
        "orient", "original", "orphan", "ostrich", "other", "outdoor", "outer", "output", "outside", "oval",
        "oven", "over", "own", "owner", "oxygen", "oyster", "ozone", "pact", "paddle", "page",
        "pair", "palace", "palm", "panda", "panel", "panic", "panther", "paper", "parade", "parent",
        "park", "parrot", "party", "pass", "patch", "path", "patient", "patrol", "pattern", "pause",
        "pave", "payment", "peace", "peanut", "pear", "peasant", "pelican", "pen", "penalty", "pencil",
        "people", "pepper", "perfect", "permit", "person", "pet", "phone", "photo", "phrase", "physical",
        "piano", "picnic", "picture", "piece", "pig", "pigeon", "pill", "pilot", "pin", "pine",
        "pink", "pipe", "pistol", "pitch", "pizza", "place", "planet", "plastic", "plate", "play",
        "please", "pledge", "pluck", "plug", "plunge", "poem", "poet", "point", "polar", "pole",
        "police", "policy", "polish", "pond", "pony", "pool", "popular", "portion", "position", "possible",
        "post", "potato", "pottery", "poverty", "powder", "power", "practice", "praise", "predict", "prefer",
        "prepare", "present", "pretty", "prevent", "price", "pride", "primary", "print", "priority", "prison",
        "private", "prize", "problem", "process", "produce", "profit", "program", "project", "promote", "proof",
        "property", "prosper", "protect", "proud", "provide", "public", "pudding", "pull", "pulp", "pulse",
        "pumpkin", "punch", "pupil", "puppy", "purchase", "purity", "purpose", "purse", "push", "put",
        "puzzle", "pyramid", "quality", "quantum", "quarter", "question", "quick", "quit", "quiz", "quote",
        "rabbit", "raccoon", "race", "rack", "radar", "radio", "rail", "rain", "raise", "rally",
        "ramp", "ranch", "random", "range", "rapid", "rare", "rate", "rather", "raven", "raw",
        "razor", "ready", "real", "reason", "rebel", "rebuild", "recall", "receive", "recipe", "record",
        "recycle", "reduce", "reflect", "reform", "refuse", "region", "regret", "regular", "reject", "relax",
        "release", "relief", "rely", "remain", "remember", "remind", "remove", "render", "renew", "rent",
        "reopen", "repair", "repeat", "replace", "report", "require", "rescue", "resemble", "resist", "resource",
        "response", "result", "retire", "retreat", "return", "reunion", "reveal", "review", "reward", "rhythm",
        "rib", "ribbon", "rice", "rich", "ride", "ridge", "rifle", "right", "rigid", "ring",
        "riot", "ripple", "risk", "ritual", "rival", "river", "road", "roast", "robot", "robust",
        "rocket", "romance", "roof", "rookie", "room", "rose", "rotate", "rough", "round", "route",
        "royal", "rubber", "rude", "rug", "rule", "run", "runway", "rural", "sad", "saddle",
        "sadness", "safe", "sail", "salad", "salmon", "salon", "salt", "salute", "same", "sample",
        "sand", "satisfy", "satoshi", "sauce", "sausage", "save", "say", "scale", "scan", "scare",
        "scatter", "scene", "scheme", "school", "science", "scissors", "scooter", "scope", "score", "scout",
        "scrap", "screen", "script", "scrub", "sea", "search", "season", "seat", "second", "secret",
        "section", "security", "seed", "seek", "segment", "select", "sell", "seminar", "senior", "sense",
        "sentence", "series", "service", "session", "settle", "setup", "seven", "shadow", "shaft", "shallow",
        "share", "shed", "shell", "sheriff", "shield", "shift", "shine", "ship", "shiver", "shock",
        "shoe", "shoot", "shop", "short", "shoulder", "shove", "shrimp", "shrug", "shuffle", "shy",
        "sibling", "sick", "side", "siege", "sight", "sign", "silent", "silk", "silly", "silver",
        "similar", "simple", "since", "sing", "siren", "sister", "situate", "six", "size", "skate",
        "sketch", "ski", "skill", "skin", "skirt", "skull", "slab", "slam", "sleep", "slender",
        "slice", "slide", "slight", "slim", "slogan", "slot", "slow", "slush", "small", "smart",
        "smile", "smoke", "smooth", "snack", "snake", "snap", "sniff", "snow", "soap", "soccer",
        "social", "sock", "soda", "soft", "solar", "soldier", "solid", "solution", "solve", "someone",
        "song", "soon", "sorry", "sort", "soul", "sound", "soup", "source", "south", "space",
        "spare", "spatial", "spawn", "speak", "special", "speed", "spell", "spend", "sphere", "spice",
        "spider", "spike", "spin", "spirit", "split", "spoil", "sponsor", "spoon", "sport", "spot",
        "spray", "spread", "spring", "spy", "square", "squeeze", "squirrel", "stable", "stadium", "staff",
        "stage", "stairs", "stamp", "stand", "start", "state", "stay", "steak", "steel", "stem",
        "step", "stereo", "stick", "still", "sting", "stock", "stomach", "stone", "stool", "story",
        "stove", "strategy", "street", "strike", "strong", "struggle", "student", "stuff", "stumble", "style",
        "subject", "submit", "subway", "success", "such", "sudden", "suffer", "sugar", "suggest", "suit",
        "summer", "sun", "sunny", "sunset", "super", "supply", "supreme", "sure", "surface", "surge",
        "surprise", "surround", "survey", "suspect", "sustain", "swallow", "swamp", "swap", "swarm", "swear",
        "sweet", "swift", "swim", "swing", "switch", "sword", "symbol", "symptom", "syrup", "system",
        "table", "tackle", "tag", "tail", "talent", "talk", "tank", "tape", "target", "task",
        "taste", "tattoo", "taxi", "teach", "team", "tell", "ten", "tenant", "tennis", "tent",
        "term", "test", "text", "thank", "that", "theme", "then", "theory", "there", "they",
        "thing", "this", "thought", "three", "thrive", "throw", "thumb", "thunder", "ticket", "tide",
        "tiger", "tilt", "timber", "time", "tiny", "tip", "tired", "tissue", "title", "toast",
        "tobacco", "today", "toddler", "toe", "together", "toilet", "token", "tomato", "tomorrow", "tone",
        "tongue", "tonight", "tool", "tooth", "top", "topic", "topple", "torch", "tornado", "tortoise",
        "toss", "total", "tourist", "toward", "tower", "town", "toy", "track", "trade", "traffic",
        "tragic", "train", "transfer", "trap", "trash", "travel", "tray", "treat", "tree", "trend",
        "trial", "tribe", "trick", "trigger", "trim", "trip", "trophy", "trouble", "truck", "true",
        "truly", "trumpet", "trust", "truth", "try", "tube", "tuition", "tumble", "tuna", "tunnel",
        "turkey", "turn", "turtle", "twelve", "twenty", "twice", "twin", "twist", "two", "type",
        "typical", "ugly", "umbrella", "unable", "unaware", "uncle", "uncover", "under", "undo", "unfair",
        "unfold", "unhappy", "uniform", "unique", "unit", "universe", "unknown", "unlock", "until", "unusual",
        "unveil", "update", "upgrade", "uphold", "upon", "upper", "upset", "urban", "urge", "usage",
        "use", "used", "useful", "useless", "usual", "utility", "vacant", "vacuum", "vague", "valid",
        "valley", "valve", "van", "vanish", "vapor", "various", "vast", "vault", "vehicle", "velvet",
        "vendor", "venture", "venue", "verb", "verify", "version", "very", "vessel", "veteran", "viable",
        "vibrant", "vicious", "victory", "video", "view", "village", "vintage", "violin", "virtual", "virus",
        "visa", "visit", "visual", "vital", "vivid", "vocal", "voice", "void", "volcano", "volume",
        "vote", "voyage", "wage", "wagon", "wait", "walk", "wall", "walnut", "want", "warfare",
        "warm", "warrior", "wash", "wasp", "waste", "water", "wave", "way", "wealth", "weapon",
        "wear", "weasel", "weather", "web", "wedding", "weekend", "weird", "welcome", "west", "wet",
        "whale", "what", "wheat", "wheel", "when", "where", "whip", "whisper", "wide", "width",
        "wife", "wild", "will", "win", "window", "wine", "wing", "wink", "winner", "winter",
        "wire", "wisdom", "wise", "wish", "witness", "wolf", "woman", "wonder", "wood", "wool",
        "word", "work", "world", "worry", "worth", "wrap", "wreck", "wrestle", "wrist", "write",
        "wrong", "yard", "year", "yellow", "you", "young", "youth", "zebra", "zero", "zone", "zoo"
    ];
}
